### ISSUE TITLE
自定义字体

### ISSUE THREAD

**Issue by MrLeihe** [MrLeihe/notes#12]
## 加载字体文件
```css
@font-face {
  font-family: 'rabbit';
  src: url('../font/rabbit.ttf');
}
```

## 使用字体
```css
.test {
  font-family: 'rabbit';
}
```
