### ISSUE TITLE
水平垂直居中

### ISSUE THREAD

**Issue by MrLeihe** [MrLeihe/notes#22]
### 实现水平垂直居中常见的的几种方式

```html
<div class="parent">
      <div class="child"></div>
</div>
```

#### 1、绝对布局

```css
.parent {
  position: relative;
  width: 100%;
  height: 200px;
  background-color: sienna;

  .child {
    position: absolute;
    width: 100px;
    height: 100px;
    background-color: rosybrown;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
  }
}

// 或者
.parent {
  position: relative;
  width: 100%;
  height: 200px;
  background-color: sienna;

  .child {
    position: absolute;
    width: 100px;
    height: 100px;
    background-color: rosybrown;
    left: 0;
    top: 0;
    right: 0;
    bottom: 0;
    margin: auto;
  }
}

// 或者
.parent {
  position: relative;
  width: 100%;
  height: 200px;
  background-color: sienna;

  .child {
    position: absolute;
    width: 100px;
    height: 100px;
    background-color: rosybrown;
    top: 50%;
    left: 50%;
    margin: -50px 0 0 -50px;
  }
}
```
#### 2、flex 布局
```css
.parent {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 100%;
  height: 200px;
  background-color: sienna;

  .child {
    width: 100px;
    height: 100px;
    background-color: rosybrown;
  }
}

// 或者
.parent {
  display: flex;
  width: 100%;
  height: 200px;
  background-color: sienna;

  .child {
    width: 100px;
    height: 100px;
    background-color: rosybrown;
    margin: auto;
  }
}
```

#### 3、grid 布局

```css
.parent {
  display: grid;
  width: 100%;
  height: 200px;
  background-color: sienna;

  .child {
    width: 100px;
    height: 100px;
    background-color: rosybrown;
    justify-self: center;
    align-self: center;
  }
}

// 或者
.parent {
  display: grid;
  width: 100%;
  height: 200px;
  background-color: sienna;

  .child {
    width: 100px;
    height: 100px;
    background-color: rosybrown;
    margin: auto;
  }
}
```

#### 4、table-cell

```css
.parent {
  display: table-cell;
  width: 100vw;
  height: 200px;
  background-color: sienna;
  text-align: center;
  vertical-align: middle;

  .child {
    display: inline-block;
    width: 100px;
    height: 100px;
    background-color: rosybrown;
  }
}
```
