### ISSUE TITLE
移动端1px边框

### ISSUE THREAD

**Issue by MrLeihe** [MrLeihe/notes#28]
## 简介
为什么移动端会出现 `1px` 问题？

如果对设备物理像素和设备逻辑像素有了解，应该能明白，为什么明明用 `css` 设置的 `1px` 高度边框 ，在屏幕上显示出来的会这么粗。因为 UI 设计师想要的是物理像素的 `1px`，而用 `css` 设置的是逻辑像素 `1px`，在设备像素比 `devicePixelRatio` 为 2 时（比如 iphone6s），逻辑像素 `1px` = 物理像素 `2px`，所以要想实现设计小姐姐需求，`css` 中，我们需要设置为` 0.5px`。

以下是基于` less` 的移动端 `1px` 实现
- 伪元素
- 多媒体查询

```css
.setMediaTransformScaleX() {
  /* 设备像素比为 2 */
  @media screen and (-webkit-min-device-pixel-ratio: 2), screen and (min-device-pixel-ratio: 2) {
    transform: scaleX(0.5);
  }
  /* 设备像素比为 3 */
  @media screen and (-webkit-min-device-pixel-ratio: 3), screen and (min-device-pixel-ratio: 3) {
    transform: scaleX(0.333333);
  }
}

.setMediaTransformScaleY() {
  @media screen and (-webkit-min-device-pixel-ratio: 2), screen and (min-device-pixel-ratio: 2) {
    transform: scaleY(0.5);
  }
  @media screen and (-webkit-min-device-pixel-ratio: 3), screen and (min-device-pixel-ratio: 3) {
    transform: scaleY(0.333333);
  }
}

.setMediaTransformScale() {
  @media screen and (-webkit-min-device-pixel-ratio: 2), screen and (min-device-pixel-ratio: 2) {
    transform: scale(0.5);
  }
  @media screen and (-webkit-min-device-pixel-ratio: 3), screen and (min-device-pixel-ratio: 3) {
    width: 300%;
    height: 300%;
    transform: scale(0.333333);
  }
}

// 上边框
.setTopLine(@c: #ededed) {
  content: '';
  position: absolute;
  left: 0;
  top: 0;
  width: 100%;
  height: 1px;
  background: @c;
  transform-origin: left top;
  transform: scaleY(0.5);
  .setMediaTransformScaleY();
}

// 下边框
.setBottomLine(@c: #ededed) {
  content: '';
  position: absolute;
  left: 0;
  bottom: 0;
  width: 100%;
  height: 1px;
  background: @c;
  transform-origin: left bottom;
  transform: scaleY(0.5);
  .setMediaTransformScaleY();
}

// 左边框
.setLeftLine(@c: #ededed) {
  content: '';
  position: absolute;
  left: 0;
  top: 0;
  width: 1px;
  height: 100%;
  background: @c;
  transform-origin: left top;
  transform: scaleX(0.5);
  .setMediaTransformScaleX();
}

// 右边框
.setRightLine(@c: #ededed) {
  content: '';
  position: absolute;
  right: 0;
  top: 0;
  width: 1px;
  height: 100%;
  background: @c;
  transform-origin: right top;
  transform: scaleX(0.5);
  .setMediaTransformScaleX();
}

// 全边框
.setBorderLine(@c: #ededed) {
  content: '';
  position: absolute;
  left: 0;
  top: 0;
  width: 200%;
  height: 200%;
  border: 1px solid @c;
  box-sizing: border-box;
  transform-origin: left top;
  transform: scale(0.5);
  .setMediaTransformScale();
}
```
